version: '3'
services:
    vault:
      environment:
          VAULT_LICENSE: $VAULT_LICENSE
      image: hashicorp/vault-enterprise:latest
      volumes:
        - ./config:/vault/config
        - ./data:/vault/file
        - ./logs:/vault/logs
      ports:
        - 8200:8200
      cap_add:
        - IPC_LOCK
      command: vault server -config=/vault/config/vault.hcl
